#
# 服务器 配置
server:
  # 端口
  port: 8080
#
# Spring Boot 配置
spring:
  #
  # 数据库 配置
  datasource:
    # 数据库 驱动名称（包括包名）
    driver-class-name: oracle.jdbc.driver.OracleDriver
    # 数据库 URL
    # ORCL：不区分大小写
    url: jdbc:oracle:thin:@192.168.15.135:1521:ORCL
    # 数据库 用户名
    username: TESTSERVICE
    # 数据库 密码
    password: TESTSERVICE
#
# MyBatis 配置
mybatis:
  # Mapper XML 文件路径
  mapper-locations: mapper/*Mapper.xml
  # 实体类路径，可在 Mapper 中使用 实体类名，而非全限定名
  type-aliases-package: cn.com.xuxiaowei.entity
#
